% Script for plotting the flow profile generated by flow.f90
% B.Dekker - ICCP 2014
clear all;
fileName = 'profile.txt';


%% Read data from file and store its contents
data=importdata(fileName); 
lY=size(data,1);

%% Calculate fitting parabola
tau = 8E-1;
visc = (2*tau - 1)/6;
deltaV = 0.0001;
c = 1; %??
curvature = c*deltaV/visc;
y = -(lY-1)/2:(lY-1)/2;
fit = -curvature*(y).^2 + curvature*(y(2)-1/2)^2; 

%% Plot data
close all;
plot(y, data(:), y, fit)
hold on;
%ax = get(fig2,'CurrentAxes');
%set(ax,'XScale','log','YScale','log')
ylabel('v')%, 'FontSize',20);   % 'FontSize',20,'position',[-1.25,0.2]));
xlabel('y')
legend('LB simulation','parabola fit')




